isEnabled = true
backgroundColor = 926762943
pressedBackgroundColor = 926762823
keyColor = -1
pressedKeyColor = -8433536
rainbowMode = false
rainbowOffset = 9
rainbowSpeed = 4
roundedBackground = false
renderInGui = true
keyShadow = false
cpsType = "ALWAYS"
displayFactor = 0.75
horizontalSlider = 439
verticalSlider = 20
showMovement = true
showJump = true
showClick = true
